/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gd_hotel.QLKS;

import com.hotel.dao.ChiTietHoaDonDAO;
import com.hotel.dao.HoaDonDAO;
import com.hotel.database.DatabaseConnection;
import com.hotel.model.ChiTietHoaDon;
import com.hotel.model.HoaDon;
import gd_hotel.MANAGER_PAGE;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOANG PHI
 */
public class HoaDon_Form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HoaDon_Form.class.getName());

    /**
     * Creates new form HoaDon_Form
     */
    public HoaDon_Form() {
        initComponents();
        
        try (Connection conn = DatabaseConnection.getConnection()) {
            DefaultTableModel model = (DefaultTableModel) tbShowHD.getModel();
            HoaDonDAO hdd = new HoaDonDAO();
            List <HoaDon> HD = hdd.getAll();
            for(HoaDon hd : HD){
                model.addRow(new Object[] {
                    hd.getMaHD(),
                    hd.getNgayLap(),
                    hd.getMaNV(),
                    hd.getMaDP()
                });
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + ex.getMessage());
        }
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Ẩn cửa sổ hiện tại
                HoaDon_Form.this.setVisible(false);

                // Mở MANAGER_PAGE
                java.awt.EventQueue.invokeLater(() -> new MANAGER_PAGE().setVisible(true));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowHD = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbShowCTHD = new javax.swing.JTable();
        btnAdd1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnFind1 = new javax.swing.JButton();
        btnAdd2 = new javax.swing.JButton();
        btnUpdate2 = new javax.swing.JButton();
        btnDelete2 = new javax.swing.JButton();
        btnFind2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbAddHD = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbShowHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HĐ", "Ngày Lập", "Mã NV", "Mã DP"
            }
        ));
        tbShowHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbShowHD);

        tbShowCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HĐ", "STT", "Nội Dung", "Số Lượng", "Đơn Giá"
            }
        ));
        jScrollPane2.setViewportView(tbShowCTHD);

        btnAdd1.setText("Thêm");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnUpdate1.setText("Sửa");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        btnDelete1.setText("Xóa");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        btnFind1.setText("Tìm");
        btnFind1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFind1ActionPerformed(evt);
            }
        });

        btnAdd2.setText("Thêm");

        btnUpdate2.setText("Sửa");

        btnDelete2.setText("Xóa");

        btnFind2.setText("Tìm");

        jPanel1.setLayout(null);

        tbAddHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Mã HĐ", "Ngày Lập", "Mã NV", "Mã DP"
            }
        ));
        tbAddHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAddHDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbAddHD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd1)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate1)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete1)
                        .addGap(18, 18, 18)
                        .addComponent(btnFind1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnAdd2)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate2)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete2)
                        .addGap(18, 18, 18)
                        .addComponent(btnFind2)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd2)
                        .addComponent(btnUpdate2)
                        .addComponent(btnDelete2)
                        .addComponent(btnFind2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd1)
                            .addComponent(btnUpdate1)
                            .addComponent(btnDelete1)
                            .addComponent(btnFind1))))
                .addGap(0, 50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void loadChiTietHoaDon(String maHD) {
        ChiTietHoaDonDAO dao = new ChiTietHoaDonDAO();
        List<ChiTietHoaDon> list = dao.getByMaHD(maHD);

        DefaultTableModel model = (DefaultTableModel) tbShowCTHD.getModel();
        model.setRowCount(0);

        for (ChiTietHoaDon ct : list) {
            model.addRow(new Object[]{
                ct.getMaHD(),
                ct.getSoThuTu(),
                ct.getNoiDung(),
                ct.getSoLuong(),
                ct.getDonGia()
            });
        }
    }

    
    private void tbShowHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowHDMouseClicked
        // TODO add your handling code here:        
        DefaultTableModel modelUpdate = (DefaultTableModel) tbAddHD.getModel();
        
        int row = tbShowHD.getSelectedRow();
        if (row >= 0) {
            String maHD = tbShowHD.getValueAt(row, 0).toString();
            loadChiTietHoaDon(maHD);
            
            modelUpdate.setRowCount(0);
            modelUpdate.addRow(new Object[]{
                tbShowHD.getValueAt(row, 0),
                tbShowHD.getValueAt(row, 1),
                tbShowHD.getValueAt(row, 2),
                tbShowHD.getValueAt(row, 3)
            });
        }
    }//GEN-LAST:event_tbShowHDMouseClicked

    // Bảng 1
    
    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        HoaDonDAO HDD = new HoaDonDAO();

        DefaultTableModel modelAdd = (DefaultTableModel) tbAddHD.getModel();
        DefaultTableModel modelShow = (DefaultTableModel) tbShowHD.getModel();

        String maHD = modelAdd.getValueAt(0, 0).toString();
        String ngayLapStr = modelAdd.getValueAt(0, 1).toString().trim();
        String maNV = modelAdd.getValueAt(0, 2).toString();
        String maDP = modelAdd.getValueAt(0, 3).toString();
        
        java.sql.Date ngayLaptmp = java.sql.Date.valueOf(ngayLapStr);
        //Timestamp ngayLaptmp = Timestamp.valueOf(ngayLapStr + " 00:00:00");

        modelShow.addRow(new Object[]{
            maHD,
            ngayLaptmp,
            maNV,
            maDP
        });

        HoaDon HD = new HoaDon();
        HD.setMaHD(maHD);
        HD.setNgayLap(ngayLaptmp);
        HD.setMaNV(maNV);
        HD.setMaDP(maDP);
        
        if (HDD.insert(HD)) {
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm!");
        }

    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        int row = tbShowHD.getSelectedRow();
        DefaultTableModel modelShow = (DefaultTableModel) tbShowHD.getModel();
        
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hóa đơn để sửa.");
            return;
        }
        
        String maHD = tbAddHD.getValueAt(0, 0).toString();
        
        java.sql.Date ngayLap;
        String ngayLapStr = tbAddHD.getValueAt(0, 1).toString();
        ngayLap = java.sql.Date.valueOf(ngayLapStr); 

        String maNV = tbAddHD.getValueAt(0, 2).toString();
        String maDP = tbAddHD.getValueAt(0, 3).toString();

        modelShow.addRow(new Object[] {
            maHD, ngayLap, maNV, maDP
        });
        
        HoaDon hd = new HoaDon(maHD, ngayLap, maNV, maDP);
        HoaDonDAO dao = new HoaDonDAO();

        if (dao.update(hd)) {
            JOptionPane.showMessageDialog(this, "Cập nhật hóa đơn thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật!");
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        int row = tbShowHD.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn dòng để xóa!");
            return;
        }

        String maHD = tbShowHD.getValueAt(row, 0).toString();

        HoaDonDAO dao = new HoaDonDAO();

        if (dao.delete(maHD)) {
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnFind1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFind1ActionPerformed
        String maHD = JOptionPane.showInputDialog("Nhập mã hóa đơn:");

        HoaDonDAO dao = new HoaDonDAO();
        HoaDon hd = dao.findById(maHD);

        DefaultTableModel model = (DefaultTableModel) tbAddHD.getModel();
        model.setRowCount(0);

        if (hd != null) {
            model.addRow(new Object[]{
                hd.getMaHD(),
                hd.getNgayLap(),
                hd.getMaNV(),
                hd.getMaDP()
            });
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy!");
        }
    }//GEN-LAST:event_btnFind1ActionPerformed

    private void tbAddHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAddHDMouseClicked
    
        int row = tbAddHD.getSelectedRow();
        if (row >= 0) {
            String maHD = tbAddHD.getValueAt(row, 0).toString();
            loadChiTietHoaDon(maHD);
            
        }
    }//GEN-LAST:event_tbAddHDMouseClicked

    
    // Bảng 2
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HoaDon_Form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnFind1;
    private javax.swing.JButton btnFind2;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbAddHD;
    private javax.swing.JTable tbShowCTHD;
    private javax.swing.JTable tbShowHD;
    // End of variables declaration//GEN-END:variables
}
