DROP DATABASE IF EXISTS BOOK_HOTEL;
CREATE DATABASE BOOK_HOTEL CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE BOOK_HOTEL;

-- 1. XÓA BẢNG CŨ (THEO THỨ TỰ NGƯỢC)
DROP TABLE IF EXISTS ChiTietHoaDon;
DROP TABLE IF EXISTS HoaDon;
DROP TABLE IF EXISTS SD_DichVu;
DROP TABLE IF EXISTS NguoiDiCung;
DROP TABLE IF EXISTS ChiTietDatPhong;
DROP TABLE IF EXISTS DatPhong;
DROP TABLE IF EXISTS Phong;
DROP TABLE IF EXISTS DichVu;
DROP TABLE IF EXISTS LoaiPhong;
DROP TABLE IF EXISTS NhanVien;
DROP TABLE IF EXISTS KhachHang;

-- 2. BẢNG DANH MỤC
CREATE TABLE KhachHang (
    MaKH VARCHAR(10) PRIMARY KEY,
    Ho VARCHAR(50) NOT NULL,
    TenLot VARCHAR(50),
    Ten VARCHAR(50) NOT NULL,
    CCCD VARCHAR(12) NOT NULL UNIQUE,
    SDT VARCHAR(15) NOT NULL UNIQUE,
    -- Không dùng NOW() trong CHECK; giữ ngưỡng cố định và kiểm tra động bằng trigger
    NamSinh INT CHECK (NamSinh > 1900),
    DiaChi VARCHAR(255),
    GioiTinh VARCHAR(10)
);

CREATE TABLE NhanVien (
    MaNV VARCHAR(10) PRIMARY KEY,
    Ho VARCHAR(50) NOT NULL,
    TenLot VARCHAR(50),
    Ten VARCHAR(50) NOT NULL,
    ChucVu VARCHAR(50),
    SDT VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE LoaiPhong (
    MaLP VARCHAR(10) PRIMARY KEY,
    TenLP VARCHAR(100) NOT NULL,
    GiaLP DECIMAL(10,2) NOT NULL CHECK (GiaLP >= 0),
    SucChua INT DEFAULT 2 CHECK (SucChua > 0),
    MoTa VARCHAR(255)
);

CREATE TABLE DichVu (
    MaDV VARCHAR(10) PRIMARY KEY,
    TenDV VARCHAR(100) NOT NULL,
    GiaDV DECIMAL(10,2) NOT NULL CHECK (GiaDV >= 0),
    MoTa VARCHAR(255)
);

-- 3. BẢNG NGHIỆP VỤ
CREATE TABLE Phong (
    MaPhong VARCHAR(10) PRIMARY KEY,
    SoPhong VARCHAR(10) NOT NULL UNIQUE,
    Tang INT CHECK (Tang > 0),
    TrangThai VARCHAR(50) DEFAULT 'Trống',
    MaLP VARCHAR(10) NOT NULL,
    MaNVQL VARCHAR(10),
    FOREIGN KEY (MaLP) REFERENCES LoaiPhong(MaLP),
    FOREIGN KEY (MaNVQL) REFERENCES NhanVien(MaNV)
);

CREATE TABLE DatPhong (
    MaDP VARCHAR(10) PRIMARY KEY,
    MaKH VARCHAR(10) NOT NULL,
    MaNV VARCHAR(10),
    NgayDat DATETIME DEFAULT NOW(),
    NgayNhan DATETIME NOT NULL,
    NgayTra DATETIME NOT NULL,
    TrangThai VARCHAR(50) DEFAULT 'Đã xác nhận',
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    CHECK (NgayNhan < NgayTra)
);

CREATE TABLE ChiTietDatPhong (
    MaDP VARCHAR(10) NOT NULL,
    MaP VARCHAR(10) NOT NULL,
    GiaDP DECIMAL(10,2) NOT NULL CHECK (GiaDP >= 0),
    PRIMARY KEY (MaDP, MaP),
    FOREIGN KEY (MaDP) REFERENCES DatPhong(MaDP) ON DELETE CASCADE,
    FOREIGN KEY (MaP) REFERENCES Phong(MaPhong)
);

CREATE TABLE NguoiDiCung (
    MaNDD VARCHAR(10) PRIMARY KEY,
    CCCD VARCHAR(12),
    HoTen VARCHAR(100) NOT NULL,
    GioiTinh VARCHAR(10),
    NamSinh INT,
    MoiQuanHe VARCHAR(50),
    MaDP VARCHAR(10) NOT NULL,
    FOREIGN KEY (MaDP) REFERENCES DatPhong(MaDP) ON DELETE CASCADE
);

CREATE TABLE SD_DichVu (
    MaDP VARCHAR(10) NOT NULL,
    MaDV VARCHAR(10) NOT NULL,
    NgaySD DATETIME NOT NULL DEFAULT NOW(),
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    PRIMARY KEY (MaDP, MaDV, NgaySD),
    FOREIGN KEY (MaDP) REFERENCES DatPhong(MaDP) ON DELETE CASCADE,
    FOREIGN KEY (MaDV) REFERENCES DichVu(MaDV)
);

CREATE TABLE HoaDon (
    MaHD VARCHAR(10) PRIMARY KEY,
    NgayLap DATETIME DEFAULT NOW(),
    MaNV VARCHAR(10) NOT NULL,
    MaDP VARCHAR(10) NOT NULL UNIQUE,
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    FOREIGN KEY (MaDP) REFERENCES DatPhong(MaDP)
);

CREATE TABLE ChiTietHoaDon (
    MaHD VARCHAR(10) NOT NULL,
    SoThuTu INT NOT NULL,
    NoiDung VARCHAR(255),
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    DonGia DECIMAL(10,2) NOT NULL CHECK (DonGia >= 0),
    PRIMARY KEY (MaHD, SoThuTu),
    FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD) ON DELETE CASCADE
);

-- 4. TRIGGER KIỂM TRA NĂM SINH THEO NĂM HIỆN TẠI
DELIMITER //

CREATE TRIGGER khachhang_chk_namsinh_ins
BEFORE INSERT ON KhachHang
FOR EACH ROW
BEGIN
    IF NEW.NamSinh IS NOT NULL AND (NEW.NamSinh <= 1900 OR NEW.NamSinh >= YEAR(CURDATE())) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NamSinh phải > 1900 và < năm hiện tại';
    END IF;
END;
//

CREATE TRIGGER khachhang_chk_namsinh_upd
BEFORE UPDATE ON KhachHang
FOR EACH ROW
BEGIN
    IF NEW.NamSinh IS NOT NULL AND (NEW.NamSinh <= 1900 OR NEW.NamSinh >= YEAR(CURDATE())) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NamSinh phải > 1900 và < năm hiện tại';
    END IF;
END;
//

DELIMITER ;
