/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gd_hotel;

import gd_hotel.QLKS.TT_KHACHHANG;
import gd_hotel.QLKS.DatPhong_Form;
import gd_hotel.QLKS.DichVu_Form;
import gd_hotel.QLKS.HoaDon_Form;
import gd_hotel.QLKS.NhanVien_Form;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author HOANG PHI
 */
public class MANAGER_PAGE extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MANAGER_PAGE.class.getName());

    /**
     * Creates new form MANAGER
     */
    public MANAGER_PAGE() {
        initComponents();
        
        popupManager = new JPopupMenu();
        
        JMenuItem item1 = new JMenuItem("Thông Tin Cá Nhân");
        JMenuItem item2 = new JMenuItem("Thông Tin Khách Hàng");
        JMenuItem item3 = new JMenuItem("Thông Tin Nhân Viên");
        JMenuItem item4 = new JMenuItem("Hóa Đơn");
        JMenuItem item5 = new JMenuItem("Thống Kê Doanh Thu");
        JMenuItem item6 = new JMenuItem("Đặt Phòng");
        JMenuItem item7 = new JMenuItem("Dịch Vụ");
        JMenuItem itemOut = new JMenuItem("Đăng Xuất");
        
        popupManager.add(item1);
        popupManager.add(item2);
        popupManager.add(item3);
        popupManager.add(item4);
        popupManager.add(item5);
        popupManager.add(item6);
        popupManager.add(item7);
        popupManager.add(itemOut);
        
        item1.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "Họ Tên: Nguyễn Văn ABC" + "\nChức Vụ: Quản Lý"
            + "\nSĐT: 0123456789","",JOptionPane.INFORMATION_MESSAGE);
        });
        
        item2.addActionListener(e -> {
            dispose();
            java.awt.EventQueue.invokeLater(() -> new TT_KHACHHANG().setVisible(true));
        });
        
        item3.addActionListener(e -> {
            dispose();
            java.awt.EventQueue.invokeLater(() -> new NhanVien_Form().setVisible(true));
        });
        
        item4.addActionListener(e -> {
            dispose();
            java.awt.EventQueue.invokeLater(() -> new HoaDon_Form().setVisible(true));
        });
        
        item5.addActionListener(e -> {
            dispose();
            java.awt.EventQueue.invokeLater(() -> new THONGKE_FORM().setVisible(true));
        });
        
        item6.addActionListener(e ->{
            dispose();
            new DatPhong_Form().setVisible(true);
        });
        
        item7.addActionListener(e ->{
            dispose();
            new DichVu_Form().setVisible(true);
        });
        
        itemOut.addActionListener(e -> {
            int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn đăng xuất không?",
                "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Đã đăng xuất!");
                dispose(); // hoặc chuyển về màn hình đăng nhập
                java.awt.EventQueue.invokeLater(() -> new HOME_PAGE().setVisible(true));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupManager = new javax.swing.JPopupMenu();
        btnManager = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManager.setBackground(new java.awt.Color(153, 153, 153));
        btnManager.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManager.setForeground(new java.awt.Color(0, 0, 0));
        btnManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48-free-object-icons/png/48x48/User.png"))); // NOI18N
        btnManager.setText("Manager");
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/ABC HOTEL (2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed
        // TODO add your handling code here:
        popupManager.show(btnManager,0,btnManager.getHeight());
    }//GEN-LAST:event_btnManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MANAGER_PAGE().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManager;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu popupManager;
    // End of variables declaration//GEN-END:variables
}
