/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gd_hotel;

import com.hotel.database.DatabaseConnectionDangKy;
import javax.swing.JOptionPane;
import gd_hotel.SIGN_UP;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author HOANG PHI
**/

public class SIGN_IN extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SIGN_IN.class.getName());

    /**
     * Creates new form SIGN_IN
     */
    public SIGN_IN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSignIn = new javax.swing.JLabel();
        lblMK = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        btnSignIn = new javax.swing.JButton();
        txtMK = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSignIn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblSignIn.setForeground(new java.awt.Color(255, 0, 102));
        lblSignIn.setText("SIGN IN");
        getContentPane().add(lblSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

        lblMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMK.setForeground(new java.awt.Color(0, 0, 0));
        lblMK.setText("Mật Khẩu:");
        getContentPane().add(lblMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, 30));

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(0, 0, 0));
        lblSDT.setText("SĐT: ");
        getContentPane().add(lblSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, 30));

        txtSDT.setBackground(new java.awt.Color(255, 255, 255));
        txtSDT.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 230, -1));

        btnSignIn.setBackground(new java.awt.Color(255, 255, 255));
        btnSignIn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(153, 255, 153));
        btnSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16-free-application-icons/16x16-free-application-icons/png/16x16/Apply.png"))); // NOI18N
        btnSignIn.setText("SIGN IN");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, -1, -1));

        txtMK.setBackground(new java.awt.Color(255, 255, 255));
        txtMK.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 230, -1));

        btnSignUp.setBackground(new java.awt.Color(255, 255, 255));
        btnSignUp.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(0, 0, 0));
        btnSignUp.setText("SIGN UP");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, 30));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/SIGN IN.png"))); // NOI18N
        lblBackGround.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // có 2 loại: User và Manager 
    boolean checkM = false;
    
    private void warn(String msg){
        JOptionPane.showMessageDialog(this, msg, "Warning", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void accountManager(String matKhau, String soDienThoai){
        if(soDienThoai.equals("0123456789") && matKhau.equals("123456789")){
            JOptionPane.showMessageDialog(this,"Thành Công!",
            "Success", JOptionPane.INFORMATION_MESSAGE);
            checkM = true;
        }
    }
    

    private void CheckSignUptoSignIn(String matKhau, String soDienThoai){
        
        String sql = "SELECT * FROM SaveTT";

        try {
            Connection conn = DatabaseConnectionDangKy.getConnection();
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            while(rs.next()){
                if(rs.getString("sdt").equals(soDienThoai) && rs.getString("mk").equals(matKhau) ){
                        // gọi USER_PAGE
                        java.awt.EventQueue.invokeLater(() -> new USER_PAGE().setVisible(true));
                        return;
                };
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Đăng Nhập Không Thành Công!","Suscess", JOptionPane.INFORMATION_MESSAGE);
        }
       
    }
    
    public static class UserSI {
        public static UserSI currentUser;
        
        private String sdt, mk;

        public String getSdt() {
            return sdt;
        }

        public void setSdt(String sdt) {
            this.sdt = sdt;
        }

        public String getMk() {
            return mk;
        }

        public void setMk(String mk) {
            this.mk = mk;
        }
        
    }
    
    private void SignIn(){
        String matKhau = txtMK.getText().trim();
        String soDienThoai = txtSDT.getText().trim();
        UserSI usSI = new UserSI();
        usSI.setSdt(soDienThoai); usSI.setMk(matKhau);
        UserSI.currentUser = usSI;
        
        if(soDienThoai.isEmpty()){warn("Chưa nhập số điện thoại!"); return;}
        else if (!soDienThoai.matches("[0-9]+")){warn("Số điện thoại không hợp lệ!");return;}
        if(matKhau.isEmpty()){warn("Chưa nhập mật khẩu!"); return;}
        
        accountManager(matKhau, soDienThoai);
        if(checkM == true){
            dispose();
            java.awt.EventQueue.invokeLater(() -> new MANAGER_PAGE().setVisible(true));
            return;
        }
        
        CheckSignUptoSignIn(matKhau, soDienThoai);
    }
    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        SignIn();
        
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> new SIGN_UP().setVisible(true));
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SIGN_IN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblMK;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
