/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gd_hotel;

import com.hotel.database.DatabaseConnectionDangKy;
import javax.swing.JOptionPane;
import gd_hotel.GD_HOTEL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author HOANG PHI
 */
public class SIGN_UP extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SIGN_UP.class.getName());

    /**
     * Creates new form SIGN_IN
     */
    public SIGN_UP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSignUp = new javax.swing.JLabel();
        lblMK = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        txtSDT = new javax.swing.JTextField();
        txtMK = new javax.swing.JPasswordField();
        lblBackGround = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSignUp.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(204, 0, 102));
        lblSignUp.setText("SIGN UP");
        getContentPane().add(lblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 110, 40));

        lblMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMK.setForeground(new java.awt.Color(0, 0, 0));
        lblMK.setText("Mật Khẩu:");
        getContentPane().add(lblMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(0, 0, 0));
        lblHoTen.setText("Họ Tên: ");
        getContentPane().add(lblHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(0, 0, 0));
        lblSDT.setText("SĐT: ");
        getContentPane().add(lblSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        txtHoTen.setBackground(new java.awt.Color(255, 255, 255));
        txtHoTen.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 220, -1));

        btnSignUp.setBackground(new java.awt.Color(255, 255, 255));
        btnSignUp.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(153, 255, 153));
        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16-free-application-icons/16x16-free-application-icons/png/16x16/Apply.png"))); // NOI18N
        btnSignUp.setText("SIGN  UP");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 120, -1));

        txtSDT.setBackground(new java.awt.Color(255, 255, 255));
        txtSDT.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 220, -1));

        txtMK.setBackground(new java.awt.Color(255, 255, 255));
        txtMK.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 304, 220, -1));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/SIGN IN.png"))); // NOI18N
        lblBackGround.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void warn(String mgs){
        JOptionPane.showMessageDialog(this, mgs, "Warning", JOptionPane.INFORMATION_MESSAGE);
    }
    
    
    
    private void SaveInfoToDataBase(String matKhau, String soDienThoai, String hoTen){ 
        String sql = "INSERT INTO SaveTT(sdt,mk,userName)" + "VALUES (?, ?, ?)";
        try (Connection conn = DatabaseConnectionDangKy.getConnection())
        {
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, soDienThoai);
            st.setString(2, matKhau);       
            st.setString(3, hoTen);
            st.executeUpdate();

            // gọi USER_PAGE
            java.awt.EventQueue.invokeLater(() -> new USER_PAGE().setVisible(true));

       } catch (SQLException ex) {
           System.err.println("Loi: " + ex.getMessage());
       }
        
    }
    
    
    private void register(){
        String hoTen = txtHoTen.getText().trim();
        String matKhau = txtMK.getText().trim();
        String soDienThoai = txtSDT.getText().trim();
        
        if(hoTen.isEmpty()){warn("Chưa nhập họ tên!"); return;}
        if(soDienThoai.isEmpty()){warn("Chưa nhập số điện thoại!"); return;}
        else if (!soDienThoai.matches("[0-9]+")){warn("Số điện thoại không hợp lệ!");}
        if(matKhau.isEmpty()){warn("Chưa nhập mật khẩu!"); return;}
        
        SaveInfoToDataBase(matKhau,soDienThoai,hoTen);

        JOptionPane.showMessageDialog(this,
            "Thông tin đăng kí: \n Họ Tên: " + hoTen +
            "\n Số Điện Thoại: " + soDienThoai + 
            "\n Mật Khẩu: " + matKhau,
            "Success", JOptionPane.INFORMATION_MESSAGE);

    }
    
    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        register();
        
        dispose();
        java.awt.EventQueue.invokeLater(() -> new SIGN_IN().setVisible(true));
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SIGN_UP().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMK;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
